# Generated by Django 3.1.5 on 2021-01-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='rate',
            new_name='rate_of_pay',
        ),
    ]
