# Generated by Django 3.1.5 on 2021-01-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20210122_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_summary',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
