# Generated by Django 3.1.5 on 2021-01-23 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_career_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='06/02/21', max_length=12),
        ),
        migrations.AddField(
            model_name='career',
            name='job_average_weekly_hours',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='career',
            name='job_contract_type',
            field=models.CharField(choices=[('FT_T', 'Full time - Temporary'), ('FT_T', 'Full time - Permanent'), ('PT_T', 'Part time - Temporary'), ('PT_T', 'Part time - Permanent')], default='PT_T', max_length=4),
        ),
        migrations.AddField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='23/01/21', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='career',
            name='job_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='job_number_of_positions',
            field=models.IntegerField(default=1, verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
