# Generated by Django 3.1.5 on 2021-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_auto_20210123_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='08/02/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_contract_type',
            field=models.CharField(choices=[('FT_T', 'Full time - Temporary'), ('FT_P', 'Full time - Permanent'), ('PT_T', 'Part time - Temporary'), ('PT_P', 'Part time - Permanent')], default='Part time - Temporary', max_length=30),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='25/01/21', editable=False, max_length=12),
        ),
    ]
