# Generated by Django 3.1.5 on 2021-01-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20210125_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='VettingApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='10/02/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_contract_type',
            field=models.CharField(choices=[('FT_T', 'Full time - Temporary'), ('FT_P', 'Full time - Permanent'), ('PT_T', 'Part time - Temporary'), ('PT_P', 'Part time - Permanent')], default='PT_T', max_length=30),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='27/01/21', editable=False, max_length=12),
        ),
        migrations.CreateModel(
            name='InterviewApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_history', models.BooleanField(default=False)),
                ('sia_badge', models.BooleanField(default=False)),
                ('sia_badges', models.CharField(choices=[('DS', 'Door Supervisor'), ('CCTV', 'CCTV'), ('CP', 'Close Protection'), ('SG', 'Security Guarding'), ('VI', 'Vehicle Immobiliser')], default='', max_length=60)),
                ('working_history', models.BooleanField(default=False)),
                ('right_to_work', models.BooleanField(default=False)),
                ('group_a', models.CharField(max_length=30)),
                ('group_b', models.CharField(max_length=30)),
                ('cv', models.FileField(upload_to='uploads/')),
                ('job_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='careers.career')),
            ],
        ),
    ]
