# Generated by Django 3.1.5 on 2021-01-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_auto_20210127_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
