# Generated by Django 3.1.5 on 2021-01-27 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0007_auto_20210127_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewapp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='job_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career'),
        ),
    ]
