# Generated by Django 3.1.5 on 2021-01-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_auto_20210128_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapp',
            name='job_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='careers.career'),
        ),
    ]
