# Generated by Django 3.1.5 on 2021-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_auto_20210128_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='number_of_applications',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='16/02/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='02/02/21', editable=False, max_length=12),
        ),
    ]
