# Generated by Django 3.1.5 on 2021-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0012_career_job_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='22/02/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='08/02/21', editable=False, max_length=12),
        ),
    ]
