# Generated by Django 3.1.5 on 2021-02-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0013_auto_20210208_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='02/03/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='16/02/21', editable=False, max_length=12),
        ),
    ]
