# Generated by Django 3.1.5 on 2021-02-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0014_auto_20210216_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_type',
            field=models.CharField(choices=[('REC', 'Receptionist'), ('SG', 'Security Guard'), ('RVRCOP', 'Control Room Operator'), ('CO', 'Cleaning Operative'), ('MD', 'Mobile Driver'), ('MS', 'Mobile Supervisor'), ('OPS', 'Operations Manager')], default='SG', max_length=30),
        ),
        migrations.AddField(
            model_name='career',
            name='vetting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='address_first_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='address_second_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='address_town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='criminal_offences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='uk_bank_account',
            field=models.BooleanField(default=False),
        ),
    ]
