# Generated by Django 3.1.5 on 2021-02-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0015_auto_20210216_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapp',
            name='group_a',
            field=models.CharField(choices=[('SVP', 'Signed Valid Passport'), ('UKBC', 'UK Birth Certificate'), ('UKDL', 'UK Driving License'), ('EUID', 'Valid EU ID Card'), ('UKFA', 'Valid UK Firearms License')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='group_b',
            field=models.CharField(choices=[('MC', 'Marriage Certificate'), ('BNC', 'British National Certificate'), ('P45', 'P45**'), ('VBWP', 'Visa or British Work Certificate'), ('P60', 'P60**'), ('DWP', 'Letter from DWP'), ('BS', 'Bank Statement*'), ('CCS', 'Credit Card Statement*'), ('MS', 'Mortgage Statement**'), ('CS', 'Court Summons**'), ('UB', 'Utility Bill*'), ('CBL', 'Child Benefit Letter**'), ('TVL', 'TV License**'), ('PSAL', 'Pay Slip with Address and Logo'), ('PS', 'Pension Statment'), ('CUKBC', 'Copy of UK Birth Certificate')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='sia_badges',
            field=models.CharField(choices=[('DS', 'Door Supervisor'), ('CCTV', 'CCTV'), ('CP', 'Close Protection'), ('SG', 'Security Guarding'), ('VI', 'Vehicle Immobiliser')], default='', max_length=100),
        ),
    ]
