# Generated by Django 3.1.5 on 2021-02-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0016_auto_20210216_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapp',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
