# Generated by Django 3.1.5 on 2021-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0017_auto_20210216_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapp',
            name='cv',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
