# Generated by Django 3.1.6 on 2021-02-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0019_auto_20210216_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapp',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/'),
        ),
    ]
