# Generated by Django 3.1.6 on 2021-02-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0020_auto_20210216_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='03/03/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='17/02/21', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='address_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='address_first_line',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='address_postcode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='address_second_line',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='address_town',
            field=models.CharField(max_length=100),
        ),
    ]
