# Generated by Django 3.1.6 on 2021-02-18 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0021_auto_20210217_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='04/03/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='18/02/21', editable=False, max_length=12),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.PositiveIntegerField()),
                ('manager_email', models.EmailField(max_length=254)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_medium', models.CharField(choices=[('TP', 'Telephone'), ('IP', 'In Person')], default='IP', max_length=50)),
                ('interview_location', models.CharField(default='', max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
