# Generated by Django 3.1.6 on 2021-02-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0024_auto_20210219_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='last_modified',
            new_name='last_modified_dt',
        ),
        migrations.AddField(
            model_name='interview',
            name='last_modified_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
