# Generated by Django 3.1.6 on 2021-02-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0025_auto_20210219_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='applicant_email',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='manager_email',
        ),
    ]
