# Generated by Django 3.1.6 on 2021-02-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0026_auto_20210219_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='result',
            field=models.SmallIntegerField(choices=[(0, 'Undecided'), (1, 'Success'), (2, 'Fail')], default=0),
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='result',
            field=models.SmallIntegerField(choices=[(0, 'Undecided'), (1, 'Success'), (2, 'Fail')], default=0),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='09/03/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='23/02/21', editable=False, max_length=12),
        ),
    ]
