# Generated by Django 3.1.7 on 2021-03-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0027_auto_20210223_0454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VettingApp',
        ),
        migrations.RenameField(
            model_name='interviewapp',
            old_name='address_city',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='interviewapp',
            old_name='address_first_line',
            new_name='first_line',
        ),
        migrations.RenameField(
            model_name='interviewapp',
            old_name='address_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='interviewapp',
            old_name='address_second_line',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='interviewapp',
            name='address_town',
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='second_line',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='19/03/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='05/03/21', editable=False, max_length=12),
        ),
    ]
