# Generated by Django 3.1.8 on 2021-06-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0029_auto_20210621_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewapp',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='email_address',
            field=models.EmailField(default='testapp@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='first_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='last_name',
            field=models.CharField(default='app', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewapp',
            name='mobile_number',
            field=models.CharField(default='07777777', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='first_line',
            field=models.CharField(help_text='First Line of Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewapp',
            name='second_line',
            field=models.CharField(blank=True, help_text='Second Line of Address', max_length=100),
        ),
    ]
