# Generated by Django 3.1.8 on 2021-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0030_auto_20210621_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewApp',
            new_name='JobApplication',
        ),
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='27/08/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='13/08/21', editable=False, max_length=12),
        ),
    ]
