# Generated by Django 3.1.8 on 2021-08-16 14:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0031_auto_20210813_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='30/08/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='16/08/21', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='sia_badges',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DS', 'Door Supervisor'), ('CCTV', 'CCTV'), ('CP', 'Close Protection'), ('SG', 'Security Guarding'), ('VI', 'Vehicle Immobiliser')], max_length=100),
        ),
    ]
