# Generated by Django 3.1.8 on 2021-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0032_auto_20210816_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='01/09/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='18/08/21', editable=False, max_length=12),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
