# Generated by Django 3.1.8 on 2021-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0034_traininginterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininginterest',
            name='course',
            field=models.CharField(choices=[('cctv', 'CCTV Operator Course'), ('guarding', 'Security Guarding Course'), ('ds', 'Door Supervisor Course'), ('cleaning', 'NHS Clinical Standard Cleaning Course'), ('reception', 'Receptionist Practice and Professionalism'), ('first aid', 'First Aid'), ('screening', 'Screening and Vetting Course'), ('weapons', 'Weapons Awareness'), ('Physical Intervention', 'Physical Intervention'), ('Fire', 'Fire Marshalling'), ('ct', 'Counter Terrorism')], default='sg', help_text='Which course interests you most?', max_length=70),
            preserve_default=False,
        ),
    ]
