# Generated by Django 3.1.13 on 2021-09-29 16:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0035_traininginterest_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='13/10/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='29/09/21', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='group_b',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MC', 'Marriage Certificate'), ('BNC', 'British National Certificate'), ('P45', 'P45**'), ('VBWP', 'Visa or British Work Certificate'), ('P60', 'P60**'), ('DWP', 'Letter from DWP'), ('BS', 'Bank Statement*'), ('CCS', 'Credit Card Statement*'), ('MS', 'Mortgage Statement**'), ('CS', 'Court Summons**'), ('UB', 'Utility Bill*'), ('CBL', 'Child Benefit Letter**'), ('TVL', 'TV License**'), ('PSAL', 'Pay Slip'), ('PS', 'Pension Statment'), ('CUKBC', 'Copy of UK Birth Certificate')], default='', max_length=300),
        ),
    ]
