# Generated by Django 3.1.13 on 2021-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0036_auto_20210929_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='10/11/21', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='27/10/21', editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='traininginterest',
            name='course',
            field=models.CharField(choices=[('siatu', 'SIA Top Up Training'), ('ds', 'Door Supervisor Course'), ('first aid', 'First Aid'), ('cctv', 'CCTV Operator Course'), ('guarding', 'Security Guarding Course'), ('cleaning', 'BICS Cleaning Course'), ('reception', 'Receptionist Practice and Professionalism'), ('ct', 'Counter Terrorism')], help_text='Which course interests you most?', max_length=70),
        ),
    ]
