# Generated by Django 3.1.13 on 2022-01-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0037_auto_20211027_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_apply_by_date',
            field=models.CharField(default='28/01/22', max_length=12),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_date_posted',
            field=models.CharField(default='14/01/22', editable=False, max_length=12),
        ),
    ]
