# Generated by Django 3.1.8 on 2021-06-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('sub_heading', models.CharField(blank=True, max_length=500)),
                ('image_main', models.ImageField(blank=True, upload_to='news/')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('order', models.IntegerField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
            ],
        ),
    ]
