# Generated by Django 3.1.8 on 2021-06-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210622_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Draft')], default=1),
        ),
    ]
