# Generated by Django 3.1.8 on 2021-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Draft'), (2, 'Deleted')], default=1),
        ),
    ]
