# Generated by Django 3.1.8 on 2021-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('HC', 'Healthcare'), ('GOV', 'Government'), ('EDU', 'Education'), ('ES', 'Emergency Services'), ('TRANS', 'Transport'), ('PROP', 'Property'), ('UTIL', 'Utilities'), ('BUSS', 'Business')], default='HC', max_length=40)),
                ('solution', models.CharField(choices=[('Automate', 'Automate my facilities processes'), ('Lock', 'Secure my buildings at night'), ('Save', 'Save money and optomise my security requirements'), ('Monitor', 'Have my CCTV and alarm systems monitored remotely'), ('Access', 'Control who has access to my buildings'), ('Risk', 'Have my security risk level assessed by a proffesional'), ('Integrate', 'Outsource my entire facilites management system'), ('FOH', 'Outsource my reception or cleaning roles')], default='Automate', max_length=100)),
            ],
        ),
    ]
