# Generated by Django 3.1.8 on 2021-07-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_solutionsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolutionSearch',
        ),
    ]
