# Generated by Django 3.1.13 on 2021-09-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_delete_solutionsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(help_text='Hello Samson ...', max_length=1000),
        ),
    ]
