# Generated by Django 3.1.5 on 2021-02-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usertype_vettingstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='user_status',
            new_name='user_type',
        ),
    ]
