# Generated by Django 3.1.5 on 2021-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210210_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'Applicant'), (1, 'Interviewee'), (2, 'Staff'), (3, 'Reserve'), (4, 'Management'), (5, 'Director')], default=0),
        ),
        migrations.AlterField(
            model_name='vettingstatus',
            name='vetting_status',
            field=models.SmallIntegerField(choices=[(0, 'Not Vetted'), (1, 'Limited Vetting'), (2, 'Fully Vetted')], default=0),
        ),
    ]
