# Generated by Django 3.1.5 on 2021-02-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210211_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_first_line',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_postcode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_second_line',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_town',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='criminal_offences',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='over_18',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='uk_bank_account',
        ),
    ]
