# Generated by Django 3.1.6 on 2021-02-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vettingstatus',
            name='vetting_status',
            field=models.SmallIntegerField(choices=[(0, 'Not Vetted'), (1, 'In Progress'), (2, 'Limited Vetting'), (3, 'Fully Vetted'), (4, 'Not Required')], default=0),
        ),
    ]
