# Generated by Django 3.1.6 on 2021-02-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210223_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vettingstatus',
            name='vetting_status',
            field=models.SmallIntegerField(choices=[(0, 'Not Vetted'), (1, 'Form Sent'), (2, 'Form Submitted'), (3, 'In Progress'), (4, 'Limited Vetting'), (5, 'Fully Vetted'), (6, 'Not Required')], default=0),
        ),
    ]
